=== DharshithaSrimal/UOK-Web-Dev-Practicals-/Web Development 2/XML/Employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Employee" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string"/>
              <xs:element name="Department">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name" type="xs:string"/>
                    <xs:element name="Location">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Country" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="DepartmentNumber" type="xs:integer"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="addresses">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="address" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Type" type="xs:string"/>
                          <xs:element name="Country" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Referrals">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Referral">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ReferralId" type="xs:integer"/>
                          <xs:element name="Name" type="xs:string"/>
                          <xs:element name="Skill" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Salary">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:decimal">
                      <xs:attribute name="Currency" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="EmployeeNumber" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== DharshithaSrimal/UOK-Web-Dev-Practicals-/Web Development 2/XML/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Employee.xsd">
    <Employee EmployeeNumber="1">
        <Name>Sam</Name>
        <Department DepartmentNumber="10">
            <Name>IT</Name>
            <Location>
                <Country>India</Country>
            </Location>
        </Department>
        <addresses>
            <address id="SN1">
                <Type>Local</Type>
                <Country>Singapore</Country>
            </address>
            <address id="SN2">
                <Type>Permanent</Type>
                <Country>India</Country>
            </address>
        </addresses>
        <Referrals>
            <Referral>
                <ReferralId>1</ReferralId>
                <Name>Andy</Name>
                <Skill>Sales</Skill>
            </Referral>
        </Referrals>
         <Salary Currency="SGD">1000</Salary>
    </Employee>
</Employees>
